---
plugin: aws_ec2
aws_access_key: ##########
aws_secret_key: #######################

regions:
  - us-east-1

filters:
  tag:Team:
#    - DevOPS
    - workers

keyed_groups:
  - key: tags.Team

hostnames:
  - ip-address

